# Generated by Django 3.2.4 on 2021-07-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_business_nature_user_nature_of_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nature_of_business',
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.IntegerField()),
                ('co2e_factor', models.FloatField(default=86.48)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ManyToManyField(related_name='business', through='users.UserBusiness', to=settings.AUTH_USER_MODEL),
        ),
    ]
