# Generated by Django 3.2.4 on 2021-07-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='co2e_factor',
            field=models.FloatField(default=116.15),
        ),
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.userbusiness'),
        ),
        migrations.AlterUniqueTogether(
            name='userbusiness',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userbusiness',
            name='co2e_factor',
        ),
        migrations.RemoveField(
            model_name='userbusiness',
            name='user',
        ),
    ]
