# Generated by Django 3.2.4 on 2021-07-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_truelayertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truelayertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='truelayer_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
