# Generated by Django 3.2.4 on 2021-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='co2e_factor',
            field=models.FloatField(default=243.72),
        ),
    ]
