# Generated by Django 3.2.4 on 2021-07-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_business_co2e_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('impact_per_member', models.FloatField(default=231.05)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='co2e_factor',
        ),
        migrations.AddField(
            model_name='business',
            name='number_of_employees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.business'),
        ),
        migrations.DeleteModel(
            name='UserBusiness',
        ),
        migrations.AlterField(
            model_name='business',
            name='nature_of_business',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='users.natureofbusiness'),
            preserve_default=False,
        ),
    ]
