# Generated by Django 3.2.4 on 2021-07-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210719_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofbusiness',
            name='impact_per_member',
            field=models.FloatField(default=53.39),
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.business'),
        ),
    ]
