# Generated by Django 3.2.4 on 2021-07-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210719_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to='users.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='natureofbusiness',
            name='impact_per_member',
            field=models.FloatField(default=141.62),
        ),
    ]
