# Generated by Django 3.2.4 on 2021-07-22 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210722_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='natureofbusiness',
            name='impact_per_member',
            field=models.FloatField(default=168.42),
        ),
    ]
