# Generated by Django 3.2.4 on 2021-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210722_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofbusiness',
            name='impact_per_member',
            field=models.FloatField(default=77.17),
        ),
    ]
