# Generated by Django 3.2.4 on 2021-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_natureofbusiness_impact_per_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofbusiness',
            name='impact_per_member',
            field=models.FloatField(default=20.16),
        ),
    ]
