# Generated by Django 3.2.4 on 2021-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='provider',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='provider',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='classsification',
            name='co2e_factor',
            field=models.FloatField(default=268.37),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=248.11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meta',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='running_balance',
            field=models.JSONField(),
        ),
    ]
