# Generated by Django 3.2.4 on 2021-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0002_auto_20210706_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsification',
            name='co2e_factor',
            field=models.FloatField(default=138.96),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=106.58),
        ),
    ]
