# Generated by Django 3.2.4 on 2021-07-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='co2e_factor',
            field=models.FloatField(default=131.69),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=23.01),
        ),
    ]
