# Generated by Django 3.2.4 on 2021-07-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0006_auto_20210718_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='co2e_factor',
            field=models.FloatField(default=18.02),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=131.56),
        ),
    ]
