# Generated by Django 3.2.4 on 2021-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0009_auto_20210719_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='co2e_factor',
            field=models.FloatField(default=173.05),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=179.64),
        ),
    ]
