# Generated by Django 3.2.4 on 2021-07-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0010_auto_20210722_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='co2e_factor',
            field=models.FloatField(default=240.12),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=33.77),
        ),
    ]
