# Generated by Django 3.2.4 on 2021-07-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truelayer', '0011_auto_20210722_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='co2e_factor',
            field=models.FloatField(default=121.51),
        ),
        migrations.AlterField(
            model_name='classification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='co2e_factor',
            field=models.FloatField(default=295.27),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='truelayer.merchant'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_classification',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='truelayer.classification'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('title', 'subtitle')},
        ),
    ]
